name: fetcher
description: Flutter package to Fetch and display asynchronous data easily
version: 4.3.1
repository: https://github.com/IcySunStudio/fetcher
issue_tracker: https://github.com/IcySunStudio/fetcher/issues

environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Framework Tools
  value_stream_flutter: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
