name: fetcher
description: Flutter package to Fetch and display asynchronous data easily
version: 0.0.3
repository: https://github.com/IcySunStudio/fetcher
issue_tracker: https://github.com/IcySunStudio/fetcher/issues

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Framework Tools
  rxdart: 0.26.0  # Stuck on this version for now : https://github.com/ReactiveX/rxdart/issues/603

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
