name: fetcher
description: Flutter package to Fetch and display asynchronous data easily
version: 3.1.0
repository: https://github.com/IcySunStudio/fetcher
issue_tracker: https://github.com/IcySunStudio/fetcher/issues

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Framework Tools
  value_stream: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
